### ISSUE TITLE
Missing information about the two Congo 

### ISSUE THREAD

**Issue by Pamphilemkp** [ridwanediallo/The-Countries#5]
Hey can you fix the population of DR Congo🇨🇩  
The population is estimated at  92.4 million persons while the population of Republic of Congo 🇨🇬 is just estimated at 2,470,000 persons !! 
Thus DR Congo 🇨🇩  is the second most populous country   in Africa after Nigeria 🇳🇬

**Comment by ridwanediallo** [comment]
Thank you @Pamphilemkp for raising the issue and for providing the correct population size for the two countries.
I am going the raise an issue too in the API documentation to let them know about it so they can fix it.
